INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1000,1,30);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1000,8,75);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1000,10,55);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1100,4,40);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1100,6,45);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1100,1,25);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1200,2,20);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1200,4,45);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1200,5,40);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1300,1,35);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1300,8,80);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1300,10,50);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1400,4,15);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1400,5,10);
INSERT INTO ASSIGNMENT(PROJECTID, EMPLOYEENUMBER, HOURSWORKED) VALUES 	(1400,6,27.5);


SELECT * FROM ASSIGNMENT;
DESCRIBE ASSIGNMENT;