
/*7.4*/
CREATE TABLE DEPARTMENT (
DepartmentName		NVARCHAR(35) NOT NULL
, BudgetCode			NVARCHAR(30) NOT NULL
, OfficeNumber			NVARCHAR(15) NOT NULL
, Phone						NVARCHAR(12) NOT NULL
, CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPARTMENTNAME)
);