

CREATE TABLE EMPLOYEE(
	  EmployeeNumber		INT 				NOT NULL AUTO_INCREMENT 
	, FirstName					NVARCHAR(25)		NOT NULL
	, LastName					NVARCHAR(25)		NOT NULL
	, Department					NVARCHAR(35)		NOT NULL		DEFAULT 'Human Resources'
	, Phone							NVARCHAR(12)		NOT NULL
	, EMAIL						NVARCHAR(100)		NOT NULL


, CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EmployeeNumber)
, CONSTRAINT EMPLOYEE_AK1 UNIQUE(EMAIL)
, CONSTRAINT EMPLOYEE_FKDEPARTMENT FOREIGN KEY (Department)
								REFERENCES DEPARTMENT(DepartmentName)
														ON UPDATE CASCADE
														ON DELETE NO ACTION
);



