DROP TABLE IF EXISTS ASSIGNMENT;

CREATE TABLE ASSIGNMENT(

	  ProjectID						INT				NOT NULL
	, EmployeeNumber		INT				NOT NULL
	, HoursWorked				DOUBLE 		NULL

, CONSTRAINT ASSIGNMENT_PK PRIMARY KEY (ProjectID, EmployeeNumber)
, CONSTRAINT ASSIGNMENT_FKPROJECT	FOREIGN KEY (ProjectID)
							REFERENCES PROJECT(ProjectID)
							ON UPDATE NO ACTION
							ON DELETE CASCADE
, CONSTRAINT  ASSIGNMENT_FKEMPLOYEE	FOREIGN KEY (EmployeeNumber)
							REFERENCES EMPLOYEE(EMPLOYEENUMBER)
							ON UPDATE NO ACTION
							ON DELETE NO ACTION


);